version: "3.9"
services:
  db:
    image: postgres:15
    container_name: pos_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: pospassword
      POSTGRES_DB: pos
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pos -d pos"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro

  api:
    build: ./api
    container_name: pos_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://pos:pospassword@db:5432/pos
      JWT_SECRET: supersecretjwt
      JWT_REFRESH_SECRET: supersecretrefresh
      ACCESS_TOKEN_EXPIRE_MINUTES: "15"
      REFRESH_TOKEN_EXPIRE_DAYS: "7"
      RATE_LIMIT_PER_MINUTE: "60"
      APP_ENV: docker
    ports:
      - "8000:8000"

  web:
    build: ./web
    container_name: pos_web
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  db_data: